name: 更新每日歷史資訊
on:
  schedule: 
    - cron: '* */24 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4200
    strategy:
        matrix:
          node-version: [16.13.1]  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          # cache key 包含了所有我們希望固定的資訊：OS，node 版本，以及 package-lock.json 的檔案內容，使用 hashFiles 將檔案內容轉換成字串
          key: node-modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
      - name: Install Packages
        run: test -d node_modules && echo "node_modules exists" || npm ci
 
      - run: npm run history
